### ISSUE TITLE
Hardcoded local path in go.mod

### ISSUE THREAD

**Issue by rimusz** [hickeyma/helm-2to3#1]
https://github.com/hickeyma/helm-2to3/blob/master/go.mod#L21
Is that done for the reason?
Building locally and also `go get -d github.com/hickeyma/helm-2to3` fails with:
```
go: parsing /home/usr1/go/src/helm.sh/helm/go.mod: open /home/usr1/go/src/helm.sh/helm/go.mod: no such file or directory
```

**Comment by hickeyma** [comment]
Good catch @rimusz, thanks.

**Comment by hickeyma** [comment]
Closing as #2 and #3 are merged.
