### ISSUE TITLE
Support for moving Helm 2 configuration `.helm` folder to Helm 3

### ISSUE THREAD

**Issue by hickeyma** [hickeyma/helm-2to3#12]
Raised in https://github.com/helm/helm/issues/5892#issuecomment-526403837

**Comment by rimusz** [comment]
maybe rename it to: Support for moving Helm 2 configuration .helm folder to Helm 3

**Comment by hickeyma** [comment]
@rimusz Any suggestion on the subcommand naming. First shot at it:
`helm 2to3 move config`

**Comment by rimusz** [comment]
—move-config?
also what about if there is the helm 3 home folder, clean up up and copy again?

**Comment by hickeyma** [comment]
> also what about if there is the helm 3 home folder already, clean up it and copy again?
Probably have to get input on this. Should the tool be simple in its approach and just override any existing files/dirs if configuration exists? Should the plugin be used before start doing work with Helm 3 on the cluster?

**Comment by rimusz** [comment]
yup, just override it, of course  we need to statė it very clearly in the docs

**Comment by rimusz** [comment]
the plugin needs to be sample and easy to use 😃

**Comment by rimusz** [comment]
also it makes sense to add an optional env var HELM_V2_HOME which could be provided if the  .helm folder is set not to the default location

**Comment by rimusz** [comment]
Implemented in #18

**Comment by hickeyma** [comment]
As per the comment in https://github.com/hickeyma/helm-2to3/pull/20#pullrequestreview-285582938, changes applied in #21
