### ISSUE TITLE
cut a first release 

### ISSUE THREAD

**Issue by rimusz** [hickeyma/helm-2to3#13]
i think it would make a sense to cut first plugin release with binaries for linux, mac and windows, so users don’t have to do that themselves and it also would lover the entrance bar for the plugin usage and testing.

goreleaser would be good candidate to automate that :)

**Comment by hickeyma** [comment]
@rimusz I think this is a good idea.

**Comment by rimusz** [comment]
covered in #18

**Comment by hickeyma** [comment]
Closing as #22 has merged.

**Comment by hickeyma** [comment]
Closed when kicked off a release build using hooks added in #22
