### ISSUE TITLE
Support multi OS on plugin install, upgrade 

### ISSUE THREAD

**Issue by rimusz** [hickeyma/helm-2to3#15]
Add plugin install, upgrade hooks to call a shell script which will download binary for currently used OS.

**Comment by rimusz** [comment]
a nice script example https://github.com/chartmuseum/helm-push/blob/master/scripts/install_plugin.sh

**Comment by rimusz** [comment]
Solved in #18

**Comment by hickeyma** [comment]
Closing as #22 has merged.
