### ISSUE TITLE
Upgrade to helm v.3.0.0-beta

### ISSUE THREAD

**Issue by slenky** [hickeyma/helm-2to3#8]
All the migrated charts doesn't appear in ```helm ls -n ${ns}``` in Helm v.3.0.0-beta.1 

Could you please upgrade the plugin?

**Comment by slenky** [comment]
PR GH-9 did a trick for me and now I see migrated release. However, I am not a Go developer so mostly what I did is 'change things until they start to work' :) 

BR,
Bohdan

**Comment by hickeyma** [comment]
@slenky Thanks for raising this PR. The plugin has an issue because there were changes in the release metadata from Helm 3 alpha to beta. lets get the updated delivered in PR #9 that you have pushed.
